name: Test application generation

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prettier-check:
    name: Prettier check
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: ${{ secrets.SKIP_ENV_VALIDATION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup npm
        uses: npm/action-setup@v2
        with:
          version: 8.10.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run prettier check
        run: npm prettier:check

  eslint-check:
    name: Eslint check
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: ${{ secrets.SKIP_ENV_VALIDATION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup npm
        uses: npm/action-setup@v2
        with:
          version: 8.10.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run eslint check
        run: npm eslint:format

  jest-check:
    name: Tests - jest
    needs: [prettier-check, eslint-check]
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: ${{ secrets.SKIP_ENV_VALIDATION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup npm
        uses: npm/action-setup@v2
        with:
          version: 8.10.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test:ci
        env:
          CI: true

  nextjs-build-check:
    name: Build nextjs application
    needs: [jest-check]
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: ${{ secrets.SKIP_ENV_VALIDATION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup npm
        uses: npm/action-setup@v2
        with:
          version: 8.10.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build nextjs
        run: npm build
        env:
          CI: true

  storybook-build-check:
    name: Build storybook application
    needs: [jest-check]
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: ${{ secrets.SKIP_ENV_VALIDATION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup npm
        uses: npm/action-setup@v2
        with:
          version: 8.10.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build storybook
        run: npm storybook:build
        env:
          CI: true
